corbel-platform/corbel-composr

src/routes/phrase.js

fixed statics routes for phrase managment 

---

src/routes/phrase.js

fixed delete phrases static endpoint

---

src/middlewares/http.js

https://github.com/restify/node-restify/issues/664

fix cors preflight

---

src/lib/router.js

Added ```keymetrics``` (pmx) metrics inside execution phrases flow. Now we have metrics like phrases executed counter and counter for phrases that are being executed real time, also, I've implemented a new hook for post-execution phrases in order to add further implementations. :eyes:

added pmx metrics

---

src/app.js

Change-Id: Ibf32b41da280a7086a2a0e6c1e6180c84970ef27

custom error handlers

---

src/lib/router.js

Change-Id: Icc35e6f300015a97f6010519091cf5a9f0983963

support also v1.0 paths

---

src/config/config.json
src/lib/config.js
src/utils/bunyanLogger.js
src/utils/composrLogger.js
src/utils/folderMaker.js

It was breaking when launching with LOG_FILE= false and BUNYAN_LOG=true,
with the folderMaker solution it works

Fixes error when launching with env variables for log

---

src/routes/doc.js

Change-Id: I0b0c7c44ec822946a74900f84301440b081336e5

Add API and Model versions to documentation

---

README.md
package.json
src/config/config.json
src/lib/config.js
src/utils/bunyanLogger.js

Change-Id: Ic7dba2f33d04f85163e744324ea0137a65cc113f

Added bunyan syslog

---

package.json
test/integration/specs/getToPhraseEndpoint.test.js

Change-Id: I52ef553aec5b1d7aee5855b6a8f27c80023a3a34

updated dependencies

---

newrelic.js
src/lib/router.js
src/metrics/newrelic.js
src/middlewares/http.js

- Added event listeners to handle corbel-js request events
- Added 'transaction' class to handle new relic metrics

- New relic custom instrumentation

---

src/routes/doc.js

Change-Id: I176698c2a360ffe197593ccb93630a9a244afb95

Add Snippets documentation (provisional)

---

src/routes/doc.js

Change-Id: I760b35e571464899e9473c977fb26e14354e0904

failing build fixed

---

src/lib/engine.js

Change-Id: Ib3b6207e6b839b259d97fa0d7ec7e0d8b3f412c7

fixes worker initialization

---

src/routes/base.js

Change-Id: I7be75e84b7a259942e7a91218fd1799c5d546e6f

Fix status check

---

.travis.yml
README.md

Change-Id: Icb661d3a0b07fac9f0fef12038c1bd0947bb7e23

codeclimate

---

src/lib/rabbitMQworker.js

Change-Id: I7a43f227a286a23385cfcda79706e9266411fb9d

events on reconnection rabbit

---

.travis.yml
Gruntfile.js
README.md
package.json

Change-Id: Ia7f7d5f705ba2fb201f532cb0cf387371f4c5068

updated readme and job coveralls

---

README.md
package.json
src/lib/router.js

Change-Id: Iebb164d9d5c516dc934f6af3ff1873da1c22ddbb

Changed error handler in phrases execution

---

package.json

- Updated 'composr-core' required version

- Modified package.json

---

src/metrics/newrelic.js
test/integration/specs/headers/headersFormat.test.js
test/integration/test-suite.js

Change-Id: I3b34a4d3a688a45d4f30935f2469265fbbfb724d

test headers format

---

src/middlewares/http.js

Change-Id: Ia5ced588ff52b9a368e0d6fd22f752dfad1361f7

Accept Deviceid header

---

.travis.yml
Dockerfile
src/middlewares/http.js

Change-Id: I04c70d2a1e61ddd458e573eddb8cfac2dc8ea126

node 5.9.0 and new headers support

---

package.json
src/routes/doc.js

Change-Id: I8eb3abe8b32685e9d6d419b39ef520e55bee5764

The new core with the new docu

---

src/routes/BaseResource.endpoint.js
test/integration/specs/phrases/invalidCorbelJsRequest.error.test.js
test/integration/specs/phrases/upsertPhrase.test.js
test/integration/specs/snippets/upsertSnippet.test.js

Change-Id: I68ce467994f7af8b0c494ece58beca9f72741beb

fixes test

---

LICENSE

Change-Id: I50d31e956aabf0c2ed33a4bb09889f02dad58fa7

updated license from Apache to Unlicense

---

.travis.yml
Dockerfile
package.json

Change-Id: I29e73898d3f89b6e2c898e6fa328c1693b14ae89

updated node js version and composr-core version

---

Gruntfile.js
package.json
src/lib/phraseHooks/validateHook.js
test/runner.js

Change-Id: I9690509e87e44540b53e244a849f3915888cc7a4

Fix body schema validation on Validation Hook

---

config/custom-environment-variables.json
package.json

Change-Id: Ief747843f9010fc44fb96f6a999c7925af139f0d

Update corbel-js version

---

src/lib/connectors/redis.js
src/lib/modules/cache.js
src/lib/router.js
test/fixtures/phrases/phraseCacheInvalidate.json
test/fixtures/phrases/phraseCacheProfile.json
test/fixtures/phrases/phraseCacheUser.json
test/integration/specs/phrases/cacheInvalidation.test.js
test/integration/test-suite.js
test/unit/specs/modules/cache.spec.js

Change-Id: I495e85197ad0e145ccc93de625c319577f63c6a0

Add invalidation support, only with wildcards
